### ISSUE TITLE
Stylesheet not regenerating when imported underscore stylesheet is saved

### ISSUE THREAD

**Issue by jstcki** [docpad/docpad-plugin-sass#13]
I have something like

``` scss
// a.css.scss
import "b";
body {
  color: $text-color;
}
```

and

``` scss
// _b.scss
$text-color: red;
```

When I change `_b.scss`, `a.css` doesn't get regenerated. I have to manually save `a.css.scss`, in order for `a.css` to be updated.
